name: MinEmacs modules check

on:
  push:
  pull_request:
  workflow_dispatch:
  # Run weekly
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 29.1
      # Install dependencies for vterm...
      - name: Install dependency needed for some Emacs packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool-bin cmake tree
      - name: Show the workspace
        run: |
          echo "Current work directory: $(pwd)"
          echo "Content"
          tree
      - name: Running Emacs
        run: |
          ln -s "$(pwd)" "../.emacs.d"
          echo "Enabling all MinEmacs modules"
          mkdir ../.minemacs.d/
          cp .github/workflows/test-confs/modules-all.el ../.minemacs.d/modules.el
          echo "Running Emacs with MinEmacs configuration"
          RUN_DATA=$(MINEMACS_VERBOSE=1 MINEMACS_CI=1 HOME=$GITHUB_WORKSPACE/.. emacs -nw --batch --script init.el 2>&1 || echo "Emacs exited with non-zero code $?")
          echo "Emacs complete output"
          echo "$RUN_DATA"
          WARNINGS=$(echo "$RUN_DATA" | grep Warning | sed -E 's/^(.*\.el)/- \*\*\1\*\*/')
          LOAD_ERRORS=$(echo "$RUN_DATA" | grep -E "(Cannot load)|(Not found)|(Debugger entered--Lisp error)" | sed 's/^/- /')
          echo -e "# MinEmacs report\n## Errors\n$LOAD_ERRORS\n## Warnings\n$WARNINGS" >> $GITHUB_STEP_SUMMARY
          [ -z "$LOAD_ERRORS" ] || exit 1
