name: Run MinEmacs with Emacs to check if it rises errors

on:
  push:
  pull_request:
  workflow_dispatch:
  # Run weekly
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 29.1
      # Install dependencies for vterm...
      - name: Install system dependency needed for some Emacs packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool-bin cmake
      - name: Install dependency needed for some Emacs packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool-bin cmake tree
      - name: Show the workspace
        run: |
          echo "Current work directory: $(pwd)"
          echo "Content"
          tree
      - name: Running Emacs
        run: |
          ln -s "$(pwd)" "../.emacs.d"
          mkdir ../.minemacs.d/
          cp .github/workflows/test-confs/modules-all.el ../.minemacs.d/modules.el
          MINEMACS_CI=1 HOME=$GITHUB_WORKSPACE/.. emacs --no-window-system --batch --script init.el 2>&1
