name: CI Windows

on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "skel/**"
  pull_request:
  workflow_dispatch:
  # Run weekly
  schedule:
    - cron: "0 0 * * 0"

jobs:
  ci-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Emacs (Windows)
        run: |
          choco install emacs
      - name: Show Emacs version
        run: |
          emacs --version
      - name: Running MinEmacs with all modules
        run: |
          $env:HOME = "D:\a\minemacs\"
          $env:MINEMACSDIR = "D:\a\minemacs\.github\workflows\scripts\minemacs-all.d\"
          emacs --no-window-system --batch --script .github\workflows\scripts\ci-init.el
      - name: Running MinEmacs in always demand mode
        run: |
          echo "Loading Emacs with MINEMACS_ALWAYS_DEMAND"
          $env:HOME = "D:\a\minemacs\"
          $env:MINEMACS_ALWAYS_DEMAND = "1"
          emacs --no-window-system --batch --script .github\workflows\scripts\ci-init.el
      - name: Running MinEmacs in daemon mode
        run: |
          echo "Loading Emacs in daemon mode"
          $env:MINEMACSDIR = "D:\a\minemacs\.github\workflows\scripts\minemacs-all.d\"
          emacs --daemon --script .github\workflows\scripts\ci-init.el
          echo "Finished"
